### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by dancju** [disroop/vs-code-conan#135]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/3108734/156633999-4dd15f35-0c3b-4ee6-a1e4-66855072bb4b.png">

https://code.visualstudio.com/api/references/activation-events#onCommand

**Comment by AdhTri001** [comment]
Same issue.

**Comment by hwhsu1231** [comment]
Neither am I. (on Windows)

![圖片 4](https://user-images.githubusercontent.com/71438617/157004817-5d64a5d7-497f-41bc-9fbf-6411af5905c1.png)

**Comment by mymichu** [comment]
Hi, we did an update. Please use plugin version 0.8.2. Please notify me if the error is solved.

**Comment by mymichu** [comment]
I think those issues are solved with the newest version (0.8.2). I will close this Issue.
