### ISSUE TITLE
Settings in shared file for all conan projects

### ISSUE THREAD

**Issue by compiaffe** [disroop/vs-code-conan#15]
Hi, 
I'm trying your tool, but I do not want to have to add the json file to every conan repo I open.

I tried adding the the file to the global `~/.vscode` directory, but that does not seem to work. Symlinking it in seems to work, but is just as annoying.

**Comment by mymichu** [comment]
Okei I will have a look into that. This is an issue and has to be fixed

**Comment by mymichu** [comment]
In version 0.8.2 you can set the path of the vscode settings file. Explained here: https://github.com/disroop/vs-code-conan/blob/master/docs/configure.adoc
