### ISSUE TITLE
Most important feature: code indexing of conan packages

### ISSUE THREAD

**Issue by jaques-sam** [disroop/vs-code-conan#21]
Either it's broken or it doesn't exist, but the main feature for this plugin should be to have code completion and indexing of the conan packages defined in a project's conan file after hitting the `conan install` button.

It shouldn't be that hard to do, as one might implement it by adding the conan packages include directories to the vscode `includePath`s.

(I don't know much about the internals of vscode, but if it's doable and you can give me a hint...)

**Comment by SirLemyDanger** [comment]
the hint: https://github.com/disroop/vs-code-conan/issues/22

**Comment by mymichu** [comment]
This issue was moved to Issue #22. Thanks you for your idea and input. We will work on it and hopefully, we can add this addon to our plugin.

**Comment by mymichu** [comment]
This issue was moved to Issue #22. Thanks you for your idea and input. We will work on it and hopefully, we can add this addon to our plugin.
