### ISSUE TITLE
Include conan profiles from a folder

### ISSUE THREAD

**Issue by finked** [disroop/vs-code-conan#23]
It would be a nice improvement to directly include a folder containing all conan profiles instead of adding them to the conan-settings.json by hand. This would make the plugin much more useful in the case of having multiple conan profiles over multiple projects.

**Comment by mymichu** [comment]
Thank you for sharing your idea. I think this would be a good improvement and easier to set up a project.

**Comment by mymichu** [comment]
This is solved on version 0.8.2. There is a generate conan-settings function (https://github.com/disroop/vs-code-conan/blob/master/docs/howto.adoc)
