### ISSUE TITLE
Changes in conan-settings.json are only applied after reopening folder

### ISSUE THREAD

**Issue by chausner-audeering** [disroop/vs-code-conan#4]
Currently, when opening a folder where `conan-settings.json` does not exist yet, even after creating the file, the extension cannot be used until closing and reopening the folder.

Similary, when making changes to an existing `conan-settings.json` such as adding a new profile, the new profile does not show up in the list until the folder has been closed and reopened.

I suggest for the extension to watch for changes of the file (there's a VS Code extension API for that) and reload it.

**Comment by stefaneicher** [comment]
Thanks for your feedback! We will improve the extension with sugestion.

Christoph Hausner <notifications@github.com> schrieb am Sa., 21. Nov. 2020,
22:02:

**Comment by stefaneicher** [comment]
Note:
https://stackoverflow.com/questions/58295424/listener-for-new-file-created-in-workspace-in-vscode-extension-api

**Comment by stefaneicher** [comment]
the watcher worked on my mac but not on windows in docker.
This might be the problem https://github.com/microsoft/vscode/issues/59146
