### ISSUE TITLE
Automatically create a default conan-settings.json

### ISSUE THREAD

**Issue by chausner-audeering** [disroop/vs-code-conan#5]
Currently, the `conan-settings.json` has to be created manually. There's a good example config included in the extension readme but it is still annoying having to copy & paste and adapt it.

I suggest to include a button in the message that says that no `conan-settings.json` has been found to automatically create a default settings file.

**Comment by stefaneicher** [comment]
Thanks for the feedback. Sounds like a good idea! If you could create a PR for that would be great.. otherwise, we take it to the backlog and may add the feature in the future.

**Comment by mymichu** [comment]
The generatation of the conan-settings.json, can be done in version 0.8.2.
